# pdf_engine.py - PetaMasa.my Core PDF Document Compilation Processing Engine
import io
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_submission_pdf(compiled_text_block: str) -> bytes:
    """
    Transforms raw multi-line strings generated by the Groq AI backend 
    into a clean, print-ready, high-resolution PDF document asset.
    """
    pdf_memory_buffer = io.BytesIO()
    
    document_scaffolding = SimpleDocTemplate(
        pdf_memory_buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    base_styles = getSampleStyleSheet()
    
    formal_body_typography = ParagraphStyle(
        'FormalCivilServiceBody',
        parent=base_styles['Normal'],
        fontSize=11,
        leading=16, 
        spaceAfter=12,
        textColor='#111111' 
    )
    
    story_canvas_elements = []
    raw_lines_array = compiled_text_block.split('\n')
    
    for line_item in raw_lines_array:
        clean_text_string = line_item.strip()
        if clean_text_string:
            formatted_paragraph_item = Paragraph(clean_text_string, formal_body_typography)
            story_canvas_elements.append(formatted_paragraph_item)
        else:
            story_canvas_elements.append(Spacer(1, 6))
            
    document_scaffolding.build(story_canvas_elements)
    pdf_memory_buffer.seek(0)
    return pdf_memory_buffer.getvalue()
